<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CidadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tbcidade')->insert([
            // Acre (estcodigo: 1)
            ['cidnome' => 'Rio Branco', 'estcodigo' => 1],
            ['cidnome' => 'Cruzeiro do Sul', 'estcodigo' => 1],
            ['cidnome' => 'Sena Madureira', 'estcodigo' => 1],
            ['cidnome' => 'Tarauacá', 'estcodigo' => 1],
            ['cidnome' => 'Feijó', 'estcodigo' => 1],
            ['cidnome' => 'Brasiléia', 'estcodigo' => 1],
            ['cidnome' => 'Plácido de Castro', 'estcodigo' => 1],
            ['cidnome' => 'Xapuri', 'estcodigo' => 1],
            ['cidnome' => 'Mâncio Lima', 'estcodigo' => 1],
            ['cidnome' => 'Epitaciolândia', 'estcodigo' => 1],
            ['cidnome' => 'Porto Acre', 'estcodigo' => 1],
            ['cidnome' => 'Rodrigues Alves', 'estcodigo' => 1],
            ['cidnome' => 'Marechal Thaumaturgo', 'estcodigo' => 1],
            ['cidnome' => 'Porto Walter', 'estcodigo' => 1],
            ['cidnome' => 'Capixaba', 'estcodigo' => 1],
            
            // Alagoas (estcodigo: 2)
            ['cidnome' => 'Maceió', 'estcodigo' => 2],
            ['cidnome' => 'Arapiraca', 'estcodigo' => 2],
            ['cidnome' => 'Rio Largo', 'estcodigo' => 2],
            ['cidnome' => 'Palmeira dos Índios', 'estcodigo' => 2],
            ['cidnome' => 'União dos Palmares', 'estcodigo' => 2],
            ['cidnome' => 'Penedo', 'estcodigo' => 2],
            ['cidnome' => 'São Miguel dos Campos', 'estcodigo' => 2],
            ['cidnome' => 'Santana do Ipanema', 'estcodigo' => 2],
            ['cidnome' => 'Delmiro Gouveia', 'estcodigo' => 2],
            ['cidnome' => 'Coruripe', 'estcodigo' => 2],
            ['cidnome' => 'Campo Alegre', 'estcodigo' => 2],
            ['cidnome' => 'Teotônio Vilela', 'estcodigo' => 2],
            ['cidnome' => 'São Luís do Quitunde', 'estcodigo' => 2],
            ['cidnome' => 'Atalaia', 'estcodigo' => 2],
            ['cidnome' => 'Murici', 'estcodigo' => 2],
            ['cidnome' => 'Pilar', 'estcodigo' => 2],
            
            // Amapá (estcodigo: 3)
            ['cidnome' => 'Macapá', 'estcodigo' => 3],
            ['cidnome' => 'Santana', 'estcodigo' => 3],
            ['cidnome' => 'Laranjal do Jari', 'estcodigo' => 3],
            ['cidnome' => 'Oiapoque', 'estcodigo' => 3],
            ['cidnome' => 'Porto Grande', 'estcodigo' => 3],
            ['cidnome' => 'Mazagão', 'estcodigo' => 3],
            ['cidnome' => 'Tartarugalzinho', 'estcodigo' => 3],
            ['cidnome' => 'Pedra Branca do Amapari', 'estcodigo' => 3],
            ['cidnome' => 'Calçoene', 'estcodigo' => 3],
            ['cidnome' => 'Amapá', 'estcodigo' => 3],
            ['cidnome' => 'Ferreira Gomes', 'estcodigo' => 3],
            ['cidnome' => 'Cutias', 'estcodigo' => 3],
            ['cidnome' => 'Itaubal', 'estcodigo' => 3],
            ['cidnome' => 'Pracuúba', 'estcodigo' => 3],
            ['cidnome' => 'Serra do Navio', 'estcodigo' => 3],
            
            // Amazonas (estcodigo: 4)
            ['cidnome' => 'Manaus', 'estcodigo' => 4],
            ['cidnome' => 'Parintins', 'estcodigo' => 4],
            ['cidnome' => 'Itacoatiara', 'estcodigo' => 4],
            ['cidnome' => 'Manacapuru', 'estcodigo' => 4],
            ['cidnome' => 'Coari', 'estcodigo' => 4],
            ['cidnome' => 'Tefé', 'estcodigo' => 4],
            ['cidnome' => 'Maués', 'estcodigo' => 4],
            ['cidnome' => 'Tabatinga', 'estcodigo' => 4],
            ['cidnome' => 'Humaitá', 'estcodigo' => 4],
            ['cidnome' => 'São Gabriel da Cachoeira', 'estcodigo' => 4],
            ['cidnome' => 'Iranduba', 'estcodigo' => 4],
            ['cidnome' => 'Rio Preto da Eva', 'estcodigo' => 4],
            ['cidnome' => 'Autazes', 'estcodigo' => 4],
            ['cidnome' => 'Borba', 'estcodigo' => 4],
            ['cidnome' => 'Novo Airão', 'estcodigo' => 4],
            ['cidnome' => 'Presidente Figueiredo', 'estcodigo' => 4],
            
            // Bahia (estcodigo: 5)
            ['cidnome' => 'Salvador', 'estcodigo' => 5],
            ['cidnome' => 'Feira de Santana', 'estcodigo' => 5],
            ['cidnome' => 'Vitória da Conquista', 'estcodigo' => 5],
            ['cidnome' => 'Camaçari', 'estcodigo' => 5],
            ['cidnome' => 'Juazeiro', 'estcodigo' => 5],
            ['cidnome' => 'Itabuna', 'estcodigo' => 5],
            ['cidnome' => 'Lauro de Freitas', 'estcodigo' => 5],
            ['cidnome' => 'Ilhéus', 'estcodigo' => 5],
            ['cidnome' => 'Jequié', 'estcodigo' => 5],
            ['cidnome' => 'Teixeira de Freitas', 'estcodigo' => 5],
            ['cidnome' => 'Barreiras', 'estcodigo' => 5],
            ['cidnome' => 'Alagoinhas', 'estcodigo' => 5],
            ['cidnome' => 'Porto Seguro', 'estcodigo' => 5],
            ['cidnome' => 'Simões Filho', 'estcodigo' => 5],
            ['cidnome' => 'Paulo Afonso', 'estcodigo' => 5],
            ['cidnome' => 'Eunápolis', 'estcodigo' => 5],
            
            // Continuação para os demais estados...
            // Ceará (estcodigo: 6)
            ['cidnome' => 'Fortaleza', 'estcodigo' => 6],
            ['cidnome' => 'Caucaia', 'estcodigo' => 6],
            ['cidnome' => 'Juazeiro do Norte', 'estcodigo' => 6],
            ['cidnome' => 'Maracanaú', 'estcodigo' => 6],
            ['cidnome' => 'Sobral', 'estcodigo' => 6],
            ['cidnome' => 'Crato', 'estcodigo' => 6],
            ['cidnome' => 'Itapipoca', 'estcodigo' => 6],
            ['cidnome' => 'Maranguape', 'estcodigo' => 6],
            ['cidnome' => 'Iguatu', 'estcodigo' => 6],
            ['cidnome' => 'Quixadá', 'estcodigo' => 6],
            ['cidnome' => 'Pacatuba', 'estcodigo' => 6],
            ['cidnome' => 'Quixeramobim', 'estcodigo' => 6],
            ['cidnome' => 'Russas', 'estcodigo' => 6],
            ['cidnome' => 'Aracati', 'estcodigo' => 6],
            ['cidnome' => 'Tianguá', 'estcodigo' => 6],
            ['cidnome' => 'Canindé', 'estcodigo' => 6],
            
            // Distrito Federal (estcodigo: 7)
            ['cidnome' => 'Brasília', 'estcodigo' => 7],
            ['cidnome' => 'Ceilândia', 'estcodigo' => 7],
            ['cidnome' => 'Taguatinga', 'estcodigo' => 7],
            ['cidnome' => 'Samambaia', 'estcodigo' => 7],
            ['cidnome' => 'Planaltina', 'estcodigo' => 7],
            ['cidnome' => 'Gama', 'estcodigo' => 7],
            ['cidnome' => 'Santa Maria', 'estcodigo' => 7],
            ['cidnome' => 'São Sebastião', 'estcodigo' => 7],
            ['cidnome' => 'Sobradinho', 'estcodigo' => 7],
            ['cidnome' => 'Paranoá', 'estcodigo' => 7],
            ['cidnome' => 'Recanto das Emas', 'estcodigo' => 7],
            ['cidnome' => 'Lago Sul', 'estcodigo' => 7],
            ['cidnome' => 'Riacho Fundo', 'estcodigo' => 7],
            ['cidnome' => 'Guará', 'estcodigo' => 7],
            ['cidnome' => 'Brazlândia', 'estcodigo' => 7],
            ['cidnome' => 'Núcleo Bandeirante', 'estcodigo' => 7],
            
            // Espírito Santo (estcodigo: 8)
            ['cidnome' => 'Vitória', 'estcodigo' => 8],
            ['cidnome' => 'Vila Velha', 'estcodigo' => 8],
            ['cidnome' => 'Cariacica', 'estcodigo' => 8],
            ['cidnome' => 'Serra', 'estcodigo' => 8],
            ['cidnome' => 'Linhares', 'estcodigo' => 8],
            ['cidnome' => 'Cachoeiro de Itapemirim', 'estcodigo' => 8],
            ['cidnome' => 'São Mateus', 'estcodigo' => 8],
            ['cidnome' => 'Colatina', 'estcodigo' => 8],
            ['cidnome' => 'Aracruz', 'estcodigo' => 8],
            ['cidnome' => 'Guarapari', 'estcodigo' => 8],
            ['cidnome' => 'Viana', 'estcodigo' => 8],
            ['cidnome' => 'Nova Venécia', 'estcodigo' => 8],
            ['cidnome' => 'Barra de São Francisco', 'estcodigo' => 8],
            ['cidnome' => 'Santa Maria de Jetibá', 'estcodigo' => 8],
            ['cidnome' => 'Marataízes', 'estcodigo' => 8],
            ['cidnome' => 'Domingos Martins', 'estcodigo' => 8],
            
            // Goiás (estcodigo: 9)
            ['cidnome' => 'Goiânia', 'estcodigo' => 9],
            ['cidnome' => 'Aparecida de Goiânia', 'estcodigo' => 9],
            ['cidnome' => 'Anápolis', 'estcodigo' => 9],
            ['cidnome' => 'Rio Verde', 'estcodigo' => 9],
            ['cidnome' => 'Luziânia', 'estcodigo' => 9],
            ['cidnome' => 'Águas Lindas de Goiás', 'estcodigo' => 9],
            ['cidnome' => 'Valparaíso de Goiás', 'estcodigo' => 9],
            ['cidnome' => 'Trindade', 'estcodigo' => 9],
            ['cidnome' => 'Formosa', 'estcodigo' => 9],
            ['cidnome' => 'Novo Gama', 'estcodigo' => 9],
            ['cidnome' => 'Senador Canedo', 'estcodigo' => 9],
            ['cidnome' => 'Itumbiara', 'estcodigo' => 9],
            ['cidnome' => 'Jataí', 'estcodigo' => 9],
            ['cidnome' => 'Catalão', 'estcodigo' => 9],
            ['cidnome' => 'Planaltina', 'estcodigo' => 9],
            ['cidnome' => 'Caldas Novas', 'estcodigo' => 9],
            
            // Continuação para os demais estados...
            // Maranhão (estcodigo: 10)
            ['cidnome' => 'São Luís', 'estcodigo' => 10],
            ['cidnome' => 'Imperatriz', 'estcodigo' => 10],
            ['cidnome' => 'Timon', 'estcodigo' => 10],
            ['cidnome' => 'Caxias', 'estcodigo' => 10],
            ['cidnome' => 'São José de Ribamar', 'estcodigo' => 10],
            ['cidnome' => 'Codó', 'estcodigo' => 10],
            ['cidnome' => 'Paço do Lumiar', 'estcodigo' => 10],
            ['cidnome' => 'Açailândia', 'estcodigo' => 10],
            ['cidnome' => 'Bacabal', 'estcodigo' => 10],
            ['cidnome' => 'Balsas', 'estcodigo' => 10],
            ['cidnome' => 'Santa Inês', 'estcodigo' => 10],
            ['cidnome' => 'Barra do Corda', 'estcodigo' => 10],
            ['cidnome' => 'Pinheiro', 'estcodigo' => 10],
            ['cidnome' => 'Chapadinha', 'estcodigo' => 10],
            ['cidnome' => 'Buriticupu', 'estcodigo' => 10],
            ['cidnome' => 'Grajaú', 'estcodigo' => 10],
            
            // Mato Grosso (estcodigo: 11)
            ['cidnome' => 'Cuiabá', 'estcodigo' => 11],
            ['cidnome' => 'Várzea Grande', 'estcodigo' => 11],
            ['cidnome' => 'Rondonópolis', 'estcodigo' => 11],
            ['cidnome' => 'Sinop', 'estcodigo' => 11],
            ['cidnome' => 'Tangará da Serra', 'estcodigo' => 11],
            ['cidnome' => 'Cáceres', 'estcodigo' => 11],
            ['cidnome' => 'Sorriso', 'estcodigo' => 11],
            ['cidnome' => 'Lucas do Rio Verde', 'estcodigo' => 11],
            ['cidnome' => 'Primavera do Leste', 'estcodigo' => 11],
            ['cidnome' => 'Barra do Garças', 'estcodigo' => 11],
            ['cidnome' => 'Alta Floresta', 'estcodigo' => 11],
            ['cidnome' => 'Pontes e Lacerda', 'estcodigo' => 11],
            ['cidnome' => 'Juína', 'estcodigo' => 11],
            ['cidnome' => 'Mirassol d\'Oeste', 'estcodigo' => 11],
            ['cidnome' => 'Campo Verde', 'estcodigo' => 11],
            ['cidnome' => 'Nova Mutum', 'estcodigo' => 11],
            
            // Mato Grosso do Sul (estcodigo: 12)
            ['cidnome' => 'Campo Grande', 'estcodigo' => 12],
            ['cidnome' => 'Dourados', 'estcodigo' => 12],
            ['cidnome' => 'Três Lagoas', 'estcodigo' => 12],
            ['cidnome' => 'Corumbá', 'estcodigo' => 12],
            ['cidnome' => 'Ponta Porã', 'estcodigo' => 12],
            ['cidnome' => 'Naviraí', 'estcodigo' => 12],
            ['cidnome' => 'Nova Andradina', 'estcodigo' => 12],
            ['cidnome' => 'Aquidauana', 'estcodigo' => 12],
            ['cidnome' => 'Sidrolândia', 'estcodigo' => 12],
            ['cidnome' => 'Paranaíba', 'estcodigo' => 12],
            ['cidnome' => 'Maracaju', 'estcodigo' => 12],
            ['cidnome' => 'Amambai', 'estcodigo' => 12],
            ['cidnome' => 'Rio Brilhante', 'estcodigo' => 12],
            ['cidnome' => 'Coxim', 'estcodigo' => 12],
            ['cidnome' => 'Jardim', 'estcodigo' => 12],
            ['cidnome' => 'São Gabriel do Oeste', 'estcodigo' => 12],
            
            // Minas Gerais (estcodigo: 13)
            ['cidnome' => 'Belo Horizonte', 'estcodigo' => 13],
            ['cidnome' => 'Uberlândia', 'estcodigo' => 13],
            ['cidnome' => 'Contagem', 'estcodigo' => 13],
            ['cidnome' => 'Juiz de Fora', 'estcodigo' => 13],
            ['cidnome' => 'Montes Claros', 'estcodigo' => 13],
            ['cidnome' => 'Betim', 'estcodigo' => 13],
            ['cidnome' => 'Ribeirão das Neves', 'estcodigo' => 13],
            ['cidnome' => 'Uberaba', 'estcodigo' => 13],
            ['cidnome' => 'Governador Valadares', 'estcodigo' => 13],
            ['cidnome' => 'Ipatinga', 'estcodigo' => 13],
            ['cidnome' => 'Sete Lagoas', 'estcodigo' => 13],
            ['cidnome' => 'Divinópolis', 'estcodigo' => 13],
            ['cidnome' => 'Santa Luzia', 'estcodigo' => 13],
            ['cidnome' => 'Poços de Caldas', 'estcodigo' => 13],
            ['cidnome' => 'Patos de Minas', 'estcodigo' => 13],
            ['cidnome' => 'Pouso Alegre', 'estcodigo' => 13],
            
            // Pará (estcodigo: 14)
            ['cidnome' => 'Belém', 'estcodigo' => 14],
            ['cidnome' => 'Ananindeua', 'estcodigo' => 14],
            ['cidnome' => 'Santarém', 'estcodigo' => 14],
            ['cidnome' => 'Marabá', 'estcodigo' => 14],
            ['cidnome' => 'Castanhal', 'estcodigo' => 14],
            ['cidnome' => 'Parauapebas', 'estcodigo' => 14],
            ['cidnome' => 'Abaetetuba', 'estcodigo' => 14],
            ['cidnome' => 'Itaituba', 'estcodigo' => 14],
            ['cidnome' => 'Cametá', 'estcodigo' => 14],
            ['cidnome' => 'Bragança', 'estcodigo' => 14],
            ['cidnome' => 'São Félix do Xingu', 'estcodigo' => 14],
            ['cidnome' => 'Barcarena', 'estcodigo' => 14],
            ['cidnome' => 'Breves', 'estcodigo' => 14],
            ['cidnome' => 'Tailândia', 'estcodigo' => 14],
            ['cidnome' => 'Moju', 'estcodigo' => 14],
            ['cidnome' => 'Altamira', 'estcodigo' => 14],
            
            // Paraíba (estcodigo: 15)
            ['cidnome' => 'João Pessoa', 'estcodigo' => 15],
            ['cidnome' => 'Campina Grande', 'estcodigo' => 15],
            ['cidnome' => 'Santa Rita', 'estcodigo' => 15],
            ['cidnome' => 'Patos', 'estcodigo' => 15],
            ['cidnome' => 'Bayeux', 'estcodigo' => 15],
            ['cidnome' => 'Sousa', 'estcodigo' => 15],
            ['cidnome' => 'Cajazeiras', 'estcodigo' => 15],
            ['cidnome' => 'Guarabira', 'estcodigo' => 15],
            ['cidnome' => 'Cabedelo', 'estcodigo' => 15],
            ['cidnome' => 'Sapé', 'estcodigo' => 15],
            ['cidnome' => 'Mamanguape', 'estcodigo' => 15],
            ['cidnome' => 'Monteiro', 'estcodigo' => 15],
            ['cidnome' => 'Pombal', 'estcodigo' => 15],
            ['cidnome' => 'Itaporanga', 'estcodigo' => 15],
            ['cidnome' => 'Catolé do Rocha', 'estcodigo' => 15],
            ['cidnome' => 'Queimadas', 'estcodigo' => 15],
            
            // Paraná (estcodigo: 16)
            ['cidnome' => 'Curitiba', 'estcodigo' => 16],
            ['cidnome' => 'Londrina', 'estcodigo' => 16],
            ['cidnome' => 'Maringá', 'estcodigo' => 16],
            ['cidnome' => 'Ponta Grossa', 'estcodigo' => 16],
            ['cidnome' => 'Cascavel', 'estcodigo' => 16],
            ['cidnome' => 'São José dos Pinhais', 'estcodigo' => 16],
            ['cidnome' => 'Foz do Iguaçu', 'estcodigo' => 16],
            ['cidnome' => 'Colombo', 'estcodigo' => 16],
            ['cidnome' => 'Guarapuava', 'estcodigo' => 16],
            ['cidnome' => 'Paranaguá', 'estcodigo' => 16],
            ['cidnome' => 'Araucária', 'estcodigo' => 16],
            ['cidnome' => 'Toledo', 'estcodigo' => 16],
            ['cidnome' => 'Apucarana', 'estcodigo' => 16],
            ['cidnome' => 'Pinhais', 'estcodigo' => 16],
            ['cidnome' => 'Campo Largo', 'estcodigo' => 16],
            ['cidnome' => 'Arapongas', 'estcodigo' => 16],
            
            // Pernambuco (estcodigo: 17)
            ['cidnome' => 'Recife', 'estcodigo' => 17],
            ['cidnome' => 'Jaboatão dos Guararapes', 'estcodigo' => 17],
            ['cidnome' => 'Olinda', 'estcodigo' => 17],
            ['cidnome' => 'Caruaru', 'estcodigo' => 17],
            ['cidnome' => 'Petrolina', 'estcodigo' => 17],
            ['cidnome' => 'Paulista', 'estcodigo' => 17],
            ['cidnome' => 'Cabo de Santo Agostinho', 'estcodigo' => 17],
            ['cidnome' => 'Camaragibe', 'estcodigo' => 17],
            ['cidnome' => 'Garanhuns', 'estcodigo' => 17],
            ['cidnome' => 'Vitória de Santo Antão', 'estcodigo' => 17],
            ['cidnome' => 'Igarassu', 'estcodigo' => 17],
            ['cidnome' => 'São Lourenço da Mata', 'estcodigo' => 17],
            ['cidnome' => 'Abreu e Lima', 'estcodigo' => 17],
            ['cidnome' => 'Santa Cruz do Capibaribe', 'estcodigo' => 17],
            ['cidnome' => 'Ipojuca', 'estcodigo' => 17],
            ['cidnome' => 'Serra Talhada', 'estcodigo' => 17],
            
            // Piauí (estcodigo: 18)
            ['cidnome' => 'Teresina', 'estcodigo' => 18],
            ['cidnome' => 'Parnaíba', 'estcodigo' => 18],
            ['cidnome' => 'Picos', 'estcodigo' => 18],
            ['cidnome' => 'Piripiri', 'estcodigo' => 18],
            ['cidnome' => 'Floriano', 'estcodigo' => 18],
            ['cidnome' => 'Campo Maior', 'estcodigo' => 18],
            ['cidnome' => 'Barras', 'estcodigo' => 18],
            ['cidnome' => 'União', 'estcodigo' => 18],
            ['cidnome' => 'Altos', 'estcodigo' => 18],
            ['cidnome' => 'Esperantina', 'estcodigo' => 18],
            ['cidnome' => 'Pedro II', 'estcodigo' => 18],
            ['cidnome' => 'José de Freitas', 'estcodigo' => 18],
            ['cidnome' => 'Oeiras', 'estcodigo' => 18],
            ['cidnome' => 'Miguel Alves', 'estcodigo' => 18],
            ['cidnome' => 'São Raimundo Nonato', 'estcodigo' => 18],
            ['cidnome' => 'Cocal', 'estcodigo' => 18],
            
            // Rio de Janeiro (estcodigo: 19)
            ['cidnome' => 'Rio de Janeiro', 'estcodigo' => 19],
            ['cidnome' => 'São Gonçalo', 'estcodigo' => 19],
            ['cidnome' => 'Duque de Caxias', 'estcodigo' => 19],
            ['cidnome' => 'Nova Iguaçu', 'estcodigo' => 19],
            ['cidnome' => 'Niterói', 'estcodigo' => 19],
            ['cidnome' => 'Belford Roxo', 'estcodigo' => 19],
            ['cidnome' => 'São João de Meriti', 'estcodigo' => 19],
            ['cidnome' => 'Campos dos Goytacazes', 'estcodigo' => 19],
            ['cidnome' => 'Petrópolis', 'estcodigo' => 19],
            ['cidnome' => 'Volta Redonda', 'estcodigo' => 19],
            ['cidnome' => 'Magé', 'estcodigo' => 19],
            ['cidnome' => 'Itaboraí', 'estcodigo' => 19],
            ['cidnome' => 'Macaé', 'estcodigo' => 19],
            ['cidnome' => 'Mesquita', 'estcodigo' => 19],
            ['cidnome' => 'Cabo Frio', 'estcodigo' => 19],
            ['cidnome' => 'Angra dos Reis', 'estcodigo' => 19],
            
            // Rio Grande do Norte (estcodigo: 20)
            ['cidnome' => 'Natal', 'estcodigo' => 20],
            ['cidnome' => 'Mossoró', 'estcodigo' => 20],
            ['cidnome' => 'Parnamirim', 'estcodigo' => 20],
            ['cidnome' => 'São Gonçalo do Amarante', 'estcodigo' => 20],
            ['cidnome' => 'Macaíba', 'estcodigo' => 20],
            ['cidnome' => 'Ceará-Mirim', 'estcodigo' => 20],
            ['cidnome' => 'Caicó', 'estcodigo' => 20],
            ['cidnome' => 'Açu', 'estcodigo' => 20],
            ['cidnome' => 'Currais Novos', 'estcodigo' => 20],
            ['cidnome' => 'São José de Mipibu', 'estcodigo' => 20],
            ['cidnome' => 'Santa Cruz', 'estcodigo' => 20],
            ['cidnome' => 'Apodi', 'estcodigo' => 20],
            ['cidnome' => 'Touros', 'estcodigo' => 20],
            ['cidnome' => 'João Câmara', 'estcodigo' => 20],
            ['cidnome' => 'Pau dos Ferros', 'estcodigo' => 20],
            ['cidnome' => 'Nova Cruz', 'estcodigo' => 20],
            
            // Rio Grande do Sul (estcodigo: 21)
            ['cidnome' => 'Porto Alegre', 'estcodigo' => 21],
            ['cidnome' => 'Caxias do Sul', 'estcodigo' => 21],
            ['cidnome' => 'Pelotas', 'estcodigo' => 21],
            ['cidnome' => 'Canoas', 'estcodigo' => 21],
            ['cidnome' => 'Santa Maria', 'estcodigo' => 21],
            ['cidnome' => 'Gravataí', 'estcodigo' => 21],
            ['cidnome' => 'Viamão', 'estcodigo' => 21],
            ['cidnome' => 'Novo Hamburgo', 'estcodigo' => 21],
            ['cidnome' => 'São Leopoldo', 'estcodigo' => 21],
            ['cidnome' => 'Rio Grande', 'estcodigo' => 21],
            ['cidnome' => 'Alvorada', 'estcodigo' => 21],
            ['cidnome' => 'Passo Fundo', 'estcodigo' => 21],
            ['cidnome' => 'Sapucaia do Sul', 'estcodigo' => 21],
            ['cidnome' => 'Uruguaiana', 'estcodigo' => 21],
            ['cidnome' => 'Santa Cruz do Sul', 'estcodigo' => 21],
            ['cidnome' => 'Cachoeirinha', 'estcodigo' => 21],
            
            // Rondônia (estcodigo: 22)
            ['cidnome' => 'Porto Velho', 'estcodigo' => 22],
            ['cidnome' => 'Ji-Paraná', 'estcodigo' => 22],
            ['cidnome' => 'Ariquemes', 'estcodigo' => 22],
            ['cidnome' => 'Vilhena', 'estcodigo' => 22],
            ['cidnome' => 'Cacoal', 'estcodigo' => 22],
            ['cidnome' => 'Rolim de Moura', 'estcodigo' => 22],
            ['cidnome' => 'Jaru', 'estcodigo' => 22],
            ['cidnome' => 'Guajará-Mirim', 'estcodigo' => 22],
            ['cidnome' => 'Ouro Preto do Oeste', 'estcodigo' => 22],
            ['cidnome' => 'Pimenta Bueno', 'estcodigo' => 22],
            ['cidnome' => 'Buritis', 'estcodigo' => 22],
            ['cidnome' => 'Machadinho d\'Oeste', 'estcodigo' => 22],
            ['cidnome' => 'Espigão d\'Oeste', 'estcodigo' => 22],
            ['cidnome' => 'Nova Mamoré', 'estcodigo' => 22],
            ['cidnome' => 'Alta Floresta d\'Oeste', 'estcodigo' => 22],
            ['cidnome' => 'Presidente Médici', 'estcodigo' => 22],
            
            // Roraima (estcodigo: 23)
            ['cidnome' => 'Boa Vista', 'estcodigo' => 23],
            ['cidnome' => 'Rorainópolis', 'estcodigo' => 23],
            ['cidnome' => 'Caracaraí', 'estcodigo' => 23],
            ['cidnome' => 'Alto Alegre', 'estcodigo' => 23],
            ['cidnome' => 'Mucajaí', 'estcodigo' => 23],
            ['cidnome' => 'Cantá', 'estcodigo' => 23],
            ['cidnome' => 'Bonfim', 'estcodigo' => 23],
            ['cidnome' => 'Pacaraima', 'estcodigo' => 23],
            ['cidnome' => 'Amajari', 'estcodigo' => 23],
            ['cidnome' => 'Normandia', 'estcodigo' => 23],
            ['cidnome' => 'Iracema', 'estcodigo' => 23],
            ['cidnome' => 'Uiramutã', 'estcodigo' => 23],
            ['cidnome' => 'São João da Baliza', 'estcodigo' => 23],
            ['cidnome' => 'São Luiz', 'estcodigo' => 23],
            ['cidnome' => 'Caroebe', 'estcodigo' => 23],
            
            // Santa Catarina (estcodigo: 24)
            ['cidnome' => 'Joinville', 'estcodigo' => 24],
            ['cidnome' => 'Florianópolis', 'estcodigo' => 24],
            ['cidnome' => 'Blumenau', 'estcodigo' => 24],
            ['cidnome' => 'São José', 'estcodigo' => 24],
            ['cidnome' => 'Criciúma', 'estcodigo' => 24],
            ['cidnome' => 'Chapecó', 'estcodigo' => 24],
            ['cidnome' => 'Itajaí', 'estcodigo' => 24],
            ['cidnome' => 'Jaraguá do Sul', 'estcodigo' => 24],
            ['cidnome' => 'Palhoça', 'estcodigo' => 24],
            ['cidnome' => 'Lages', 'estcodigo' => 24],
            ['cidnome' => 'Balneário Camboriú', 'estcodigo' => 24],
            ['cidnome' => 'Brusque', 'estcodigo' => 24],
            ['cidnome' => 'Tubarão', 'estcodigo' => 24],
            ['cidnome' => 'Camboriú', 'estcodigo' => 24],
            ['cidnome' => 'Rio do Sul', 'estcodigo' => 24],
            ['cidnome' => 'Navegantes', 'estcodigo' => 24],
            ['cidnome' => 'Atalanta', 'estcodigo' => 24],
            ['cidnome' => 'Agrolandia', 'estcodigo' => 24],            
            ['cidnome' => 'Trombudo Central', 'estcodigo' => 24],            
            ['cidnome' => 'Agronomica', 'estcodigo' => 24],            
            
            // São Paulo (estcodigo: 25)
            ['cidnome' => 'São Paulo', 'estcodigo' => 25],
            ['cidnome' => 'Guarulhos', 'estcodigo' => 25],
            ['cidnome' => 'Campinas', 'estcodigo' => 25],
            ['cidnome' => 'São Bernardo do Campo', 'estcodigo' => 25],
            ['cidnome' => 'Santo André', 'estcodigo' => 25],
            ['cidnome' => 'Osasco', 'estcodigo' => 25],
            ['cidnome' => 'São José dos Campos', 'estcodigo' => 25],
            ['cidnome' => 'Ribeirão Preto', 'estcodigo' => 25],
            ['cidnome' => 'Sorocaba', 'estcodigo' => 25],
            ['cidnome' => 'Mauá', 'estcodigo' => 25],
            ['cidnome' => 'São José do Rio Preto', 'estcodigo' => 25],
            ['cidnome' => 'Mogi das Cruzes', 'estcodigo' => 25],
            ['cidnome' => 'Santos', 'estcodigo' => 25],
            ['cidnome' => 'Diadema', 'estcodigo' => 25],
            ['cidnome' => 'Jundiaí', 'estcodigo' => 25],
            ['cidnome' => 'Piracicaba', 'estcodigo' => 25],
            
            // Sergipe (estcodigo: 26)
            ['cidnome' => 'Aracaju', 'estcodigo' => 26],
            ['cidnome' => 'Nossa Senhora do Socorro', 'estcodigo' => 26],
            ['cidnome' => 'Lagarto', 'estcodigo' => 26],
            ['cidnome' => 'Itabaiana', 'estcodigo' => 26],
            ['cidnome' => 'São Cristóvão', 'estcodigo' => 26],
            ['cidnome' => 'Estância', 'estcodigo' => 26],
            ['cidnome' => 'Tobias Barreto', 'estcodigo' => 26],
            ['cidnome' => 'Itabaianinha', 'estcodigo' => 26],
            ['cidnome' => 'Simão Dias', 'estcodigo' => 26],
            ['cidnome' => 'Nossa Senhora da Glória', 'estcodigo' => 26],
            ['cidnome' => 'Poço Redondo', 'estcodigo' => 26],
            ['cidnome' => 'Capela', 'estcodigo' => 26],
            ['cidnome' => 'Propriá', 'estcodigo' => 26],
            ['cidnome' => 'Porto da Folha', 'estcodigo' => 26],
            ['cidnome' => 'Neópolis', 'estcodigo' => 26],
            ['cidnome' => 'Itaporanga d\'Ajuda', 'estcodigo' => 26],
            
            // Tocantins (estcodigo: 27)
            ['cidnome' => 'Palmas', 'estcodigo' => 27],
            ['cidnome' => 'Araguaína', 'estcodigo' => 27],
            ['cidnome' => 'Gurupi', 'estcodigo' => 27],
            ['cidnome' => 'Porto Nacional', 'estcodigo' => 27],
            ['cidnome' => 'Paraíso do Tocantins', 'estcodigo' => 27],
            ['cidnome' => 'Araguatins', 'estcodigo' => 27],
            ['cidnome' => 'Colinas do Tocantins', 'estcodigo' => 27],
            ['cidnome' => 'Guaraí', 'estcodigo' => 27],
            ['cidnome' => 'Tocantinópolis', 'estcodigo' => 27],
            ['cidnome' => 'Dianópolis', 'estcodigo' => 27],
            ['cidnome' => 'Formoso do Araguaia', 'estcodigo' => 27],
            ['cidnome' => 'Miracema do Tocantins', 'estcodigo' => 27],
            ['cidnome' => 'Augustinópolis', 'estcodigo' => 27],
            ['cidnome' => 'Pedro Afonso', 'estcodigo' => 27],
            ['cidnome' => 'Wanderlândia', 'estcodigo' => 27],
            ['cidnome' => 'Xambioá', 'estcodigo' => 27],
            
            // Outro estado (estcodigo: 28)
            ['cidnome' => 'Outra cidade', 'estcodigo' => 28]
        ]);
    }
}
