<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaisesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tbpais')->insert([
            ['painome' => 'Afeganistão', 'paisigla' => 'AF'],
            ['painome' => 'África do Sul', 'paisigla' => 'ZA'],
            ['painome' => 'Albânia', 'paisigla' => 'AL'],
            ['painome' => 'Alemanha', 'paisigla' => 'DE'],
            ['painome' => 'Andorra', 'paisigla' => 'AD'],
            ['painome' => 'Angola', 'paisigla' => 'AO'],
            ['painome' => 'Antígua e Barbuda', 'paisigla' => 'AG'],
            ['painome' => 'Arábia Saudita', 'paisigla' => 'SA'],
            ['painome' => 'Argélia', 'paisigla' => 'DZ'],
            ['painome' => 'Argentina', 'paisigla' => 'AR'],
            ['painome' => 'Armênia', 'paisigla' => 'AM'],
            ['painome' => 'Austrália', 'paisigla' => 'AU'],
            ['painome' => 'Áustria', 'paisigla' => 'AT'],
            ['painome' => 'Azerbaijão', 'paisigla' => 'AZ'],
            ['painome' => 'Bahamas', 'paisigla' => 'BS'],
            ['painome' => 'Bangladesh', 'paisigla' => 'BD'],
            ['painome' => 'Barbados', 'paisigla' => 'BB'],
            ['painome' => 'Barein', 'paisigla' => 'BH'],
            ['painome' => 'Bélgica', 'paisigla' => 'BE'],
            ['painome' => 'Belize', 'paisigla' => 'BZ'],
            ['painome' => 'Benim', 'paisigla' => 'BJ'],
            ['painome' => 'Bielorrússia', 'paisigla' => 'BY'],
            ['painome' => 'Bolívia', 'paisigla' => 'BO'],
            ['painome' => 'Bósnia e Herzegovina', 'paisigla' => 'BA'],
            ['painome' => 'Botsuana', 'paisigla' => 'BW'],
            ['painome' => 'Brasil', 'paisigla' => 'BR'],
            ['painome' => 'Brunei', 'paisigla' => 'BN'],
            ['painome' => 'Bulgária', 'paisigla' => 'BG'],
            ['painome' => 'Burkina Faso', 'paisigla' => 'BF'],
            ['painome' => 'Burundi', 'paisigla' => 'BI'],
            ['painome' => 'Butão', 'paisigla' => 'BT'],
            ['painome' => 'Cabo Verde', 'paisigla' => 'CV'],
            ['painome' => 'Camarões', 'paisigla' => 'CM'],
            ['painome' => 'Camboja', 'paisigla' => 'KH'],
            ['painome' => 'Canadá', 'paisigla' => 'CA'],
            ['painome' => 'Catar', 'paisigla' => 'QA'],
            ['painome' => 'Cazaquistão', 'paisigla' => 'KZ'],
            ['painome' => 'Chade', 'paisigla' => 'TD'],
            ['painome' => 'Chile', 'paisigla' => 'CL'],
            ['painome' => 'China', 'paisigla' => 'CN'],
            ['painome' => 'Chipre', 'paisigla' => 'CY'],
            ['painome' => 'Colômbia', 'paisigla' => 'CO'],
            ['painome' => 'Comores', 'paisigla' => 'KM'],
            ['painome' => 'Congo', 'paisigla' => 'CG'],
            ['painome' => 'Coreia do Norte', 'paisigla' => 'KP'],
            ['painome' => 'Coreia do Sul', 'paisigla' => 'KR'],
            ['painome' => 'Costa do Marfim', 'paisigla' => 'CI'],
            ['painome' => 'Costa Rica', 'paisigla' => 'CR'],
            ['painome' => 'Croácia', 'paisigla' => 'HR'],
            ['painome' => 'Cuba', 'paisigla' => 'CU'],
            ['painome' => 'Dinamarca', 'paisigla' => 'DK'],
            ['painome' => 'Djibuti', 'paisigla' => 'DJ'],
            ['painome' => 'Dominica', 'paisigla' => 'DM'],
            ['painome' => 'Egito', 'paisigla' => 'EG'],
            ['painome' => 'El Salvador', 'paisigla' => 'SV'],
            ['painome' => 'Emirados Árabes Unidos', 'paisigla' => 'AE'],
            ['painome' => 'Equador', 'paisigla' => 'EC'],
            ['painome' => 'Eritreia', 'paisigla' => 'ER'],
            ['painome' => 'Eslováquia', 'paisigla' => 'SK'],
            ['painome' => 'Eslovênia', 'paisigla' => 'SI'],
            ['painome' => 'Espanha', 'paisigla' => 'ES'],
            ['painome' => 'Estados Unidos', 'paisigla' => 'US'],
            ['painome' => 'Estônia', 'paisigla' => 'EE'],
            ['painome' => 'Eswatini', 'paisigla' => 'SZ'],
            ['painome' => 'Etiópia', 'paisigla' => 'ET'],
            ['painome' => 'Fiji', 'paisigla' => 'FJ'],
            ['painome' => 'Filipinas', 'paisigla' => 'PH'],
            ['painome' => 'Finlândia', 'paisigla' => 'FI'],
            ['painome' => 'França', 'paisigla' => 'FR'],
            ['painome' => 'Gabão', 'paisigla' => 'GA'],
            ['painome' => 'Gâmbia', 'paisigla' => 'GM'],
            ['painome' => 'Gana', 'paisigla' => 'GH'],
            ['painome' => 'Geórgia', 'paisigla' => 'GE'],
            ['painome' => 'Granada', 'paisigla' => 'GD'],
            ['painome' => 'Grécia', 'paisigla' => 'GR'],
            ['painome' => 'Guatemala', 'paisigla' => 'GT'],
            ['painome' => 'Guiana', 'paisigla' => 'GY'],
            ['painome' => 'Guiné', 'paisigla' => 'GN'],
            ['painome' => 'Guiné Equatorial', 'paisigla' => 'GQ'],
            ['painome' => 'Guiné-Bissau', 'paisigla' => 'GW'],
            ['painome' => 'Haiti', 'paisigla' => 'HT'],
            ['painome' => 'Honduras', 'paisigla' => 'HN'],
            ['painome' => 'Hungria', 'paisigla' => 'HU'],
            ['painome' => 'Iêmen', 'paisigla' => 'YE'],
            ['painome' => 'Ilhas Marshall', 'paisigla' => 'MH'],
            ['painome' => 'Ilhas Salomão', 'paisigla' => 'SB'],
            ['painome' => 'Índia', 'paisigla' => 'IN'],
            ['painome' => 'Indonésia', 'paisigla' => 'ID'],
            ['painome' => 'Irã', 'paisigla' => 'IR'],
            ['painome' => 'Iraque', 'paisigla' => 'IQ'],
            ['painome' => 'Irlanda', 'paisigla' => 'IE'],
            ['painome' => 'Islândia', 'paisigla' => 'IS'],
            ['painome' => 'Israel', 'paisigla' => 'IL'],
            ['painome' => 'Itália', 'paisigla' => 'IT'],
            ['painome' => 'Jamaica', 'paisigla' => 'JM'],
            ['painome' => 'Japão', 'paisigla' => 'JP'],
            ['painome' => 'Jordânia', 'paisigla' => 'JO'],
            ['painome' => 'Kiribati', 'paisigla' => 'KI'],
            ['painome' => 'Kuwait', 'paisigla' => 'KW'],
            ['painome' => 'Laos', 'paisigla' => 'LA'],
            ['painome' => 'Lesoto', 'paisigla' => 'LS'],
            ['painome' => 'Letônia', 'paisigla' => 'LV'],
            ['painome' => 'Líbano', 'paisigla' => 'LB'],
            ['painome' => 'Libéria', 'paisigla' => 'LR'],
            ['painome' => 'Líbia', 'paisigla' => 'LY'],
            ['painome' => 'Liechtenstein', 'paisigla' => 'LI'],
            ['painome' => 'Lituânia', 'paisigla' => 'LT'],
            ['painome' => 'Luxemburgo', 'paisigla' => 'LU'],
            ['painome' => 'Macedônia do Norte', 'paisigla' => 'MK'],
            ['painome' => 'Madagascar', 'paisigla' => 'MG'],
            ['painome' => 'Malásia', 'paisigla' => 'MY'],
            ['painome' => 'Maláui', 'paisigla' => 'MW'],
            ['painome' => 'Maldivas', 'paisigla' => 'MV'],
            ['painome' => 'Mali', 'paisigla' => 'ML'],
            ['painome' => 'Malta', 'paisigla' => 'MT'],
            ['painome' => 'Marrocos', 'paisigla' => 'MA'],
            ['painome' => 'Maurícia', 'paisigla' => 'MU'],
            ['painome' => 'Mauritânia', 'paisigla' => 'MR'],
            ['painome' => 'México', 'paisigla' => 'MX'],
            ['painome' => 'Micronésia', 'paisigla' => 'FM'],
            ['painome' => 'Moçambique', 'paisigla' => 'MZ'],
            ['painome' => 'Moldávia', 'paisigla' => 'MD'],
            ['painome' => 'Mônaco', 'paisigla' => 'MC'],
            ['painome' => 'Mongólia', 'paisigla' => 'MN'],
            ['painome' => 'Montenegro', 'paisigla' => 'ME'],
            ['painome' => 'Myanmar', 'paisigla' => 'MM'],
            ['painome' => 'Namíbia', 'paisigla' => 'NA'],
            ['painome' => 'Nauru', 'paisigla' => 'NR'],
            ['painome' => 'Nepal', 'paisigla' => 'NP'],
            ['painome' => 'Nicarágua', 'paisigla' => 'NI'],
            ['painome' => 'Níger', 'paisigla' => 'NE'],
            ['painome' => 'Nigéria', 'paisigla' => 'NG'],
            ['painome' => 'Noruega', 'paisigla' => 'NO'],
            ['painome' => 'Nova Zelândia', 'paisigla' => 'NZ'],
            ['painome' => 'Omã', 'paisigla' => 'OM'],
            ['painome' => 'Países Baixos', 'paisigla' => 'NL'],
            ['painome' => 'Palau', 'paisigla' => 'PW'],
            ['painome' => 'Panamá', 'paisigla' => 'PA'],
            ['painome' => 'Papua-Nova Guiné', 'paisigla' => 'PG'],
            ['painome' => 'Paquistão', 'paisigla' => 'PK'],
            ['painome' => 'Paraguai', 'paisigla' => 'PY'],
            ['painome' => 'Peru', 'paisigla' => 'PE'],
            ['painome' => 'Polônia', 'paisigla' => 'PL'],
            ['painome' => 'Portugal', 'paisigla' => 'PT'],
            ['painome' => 'Quênia', 'paisigla' => 'KE'],
            ['painome' => 'Quirguistão', 'paisigla' => 'KG'],
            ['painome' => 'Reino Unido', 'paisigla' => 'GB'],
            ['painome' => 'República Centro-Africana', 'paisigla' => 'CF'],
            ['painome' => 'República Democrática do Congo', 'paisigla' => 'CD'],
            ['painome' => 'República Dominicana', 'paisigla' => 'DO'],
            ['painome' => 'República Tcheca', 'paisigla' => 'CZ'],
            ['painome' => 'Romênia', 'paisigla' => 'RO'],
            ['painome' => 'Ruanda', 'paisigla' => 'RW'],
            ['painome' => 'Rússia', 'paisigla' => 'RU'],
            ['painome' => 'Samoa', 'paisigla' => 'WS'],
            ['painome' => 'San Marino', 'paisigla' => 'SM'],
            ['painome' => 'Santa Lúcia', 'paisigla' => 'LC'],
            ['painome' => 'São Cristóvão e Névis', 'paisigla' => 'KN'],
            ['painome' => 'São Tomé e Príncipe', 'paisigla' => 'ST'],
            ['painome' => 'São Vicente e Granadinas', 'paisigla' => 'VC'],
            ['painome' => 'Seicheles', 'paisigla' => 'SC'],
            ['painome' => 'Senegal', 'paisigla' => 'SN'],
            ['painome' => 'Serra Leoa', 'paisigla' => 'SL'],
            ['painome' => 'Sérvia', 'paisigla' => 'RS'],
            ['painome' => 'Singapura', 'paisigla' => 'SG'],
            ['painome' => 'Síria', 'paisigla' => 'SY'],
            ['painome' => 'Somália', 'paisigla' => 'SO'],
            ['painome' => 'Sri Lanka', 'paisigla' => 'LK'],
            ['painome' => 'Sudão', 'paisigla' => 'SD'],
            ['painome' => 'Sudão do Sul', 'paisigla' => 'SS'],
            ['painome' => 'Suécia', 'paisigla' => 'SE'],
            ['painome' => 'Suíça', 'paisigla' => 'CH'],
            ['painome' => 'Suriname', 'paisigla' => 'SR'],
            ['painome' => 'Tailândia', 'paisigla' => 'TH'],
            ['painome' => 'Taiwan', 'paisigla' => 'TW'],
            ['painome' => 'Tajiquistão', 'paisigla' => 'TJ'],
            ['painome' => 'Tanzânia', 'paisigla' => 'TZ'],
            ['painome' => 'Timor-Leste', 'paisigla' => 'TL'],
            ['painome' => 'Togo', 'paisigla' => 'TG'],
            ['painome' => 'Tonga', 'paisigla' => 'TO'],
            ['painome' => 'Trinidad e Tobago', 'paisigla' => 'TT'],
            ['painome' => 'Tunísia', 'paisigla' => 'TN'],
            ['painome' => 'Turcomenistão', 'paisigla' => 'TM'],
            ['painome' => 'Turquia', 'paisigla' => 'TR'],
            ['painome' => 'Tuvalu', 'paisigla' => 'TV'],
            ['painome' => 'Ucrânia', 'paisigla' => 'UA'],
            ['painome' => 'Uganda', 'paisigla' => 'UG'],
            ['painome' => 'Uruguai', 'paisigla' => 'UY'],
            ['painome' => 'Uzbequistão', 'paisigla' => 'UZ'],
            ['painome' => 'Vanuatu', 'paisigla' => 'VU'],
            ['painome' => 'Vaticano', 'paisigla' => 'VA'],
            ['painome' => 'Venezuela', 'paisigla' => 'VE'],
            ['painome' => 'Vietnã', 'paisigla' => 'VN'],
            ['painome' => 'Zâmbia', 'paisigla' => 'ZM'],
            ['painome' => 'Zimbábue', 'paisigla' => 'ZW'],
            ['painome' => 'Outro país', 'paisigla' => 'XX']
        ]);       
    }
}
